package io.cdap.wrangler.parser;

import io.cdap.wrangler.api.parser.Bool;
import io.cdap.wrangler.api.parser.ByteSize;
import io.cdap.wrangler.api.parser.ColumnName;
import io.cdap.wrangler.api.parser.Numeric;
import io.cdap.wrangler.api.parser.Text;
import io.cdap.wrangler.api.parser.Token;

public class GrammarWalker extends DirectivesBaseVisitor<Token> {

    @Override
    public Token visitValue(DirectivesParser.ValueContext ctx) {
        if (ctx.String() != null) {
            String value = ctx.getText();
            return new Text(value.substring(1, value.length() - 1)); // Remove quotes
        } else if (ctx.Number() != null) {
            return new Numeric(() -> Double.parseDouble(ctx.getText()));
        } else if (ctx.Bool() != null) {
            return new Bool(Boolean.parseBoolean(ctx.getText()));
        } else if (ctx.BYTE_SIZE() != null) {
            return new ByteSize(ctx.getText());
        } else if (ctx.Column() != null) {
            return new ColumnName(ctx.getText());
        } else if (ctx.functionCall() != null) {
            return visitFunctionCall(ctx.functionCall());
        }
        throw new IllegalArgumentException("Unknown value type: " + ctx.getText());
    }

    // Other methods...
}

/**
 * This class provides logic to walk a grammar tree by parsing a wrangler recipe.
 */
public class GrammarWalker {

    private final Compiler compiler;
    private final DirectiveContext context;

    /**
     * A visitor for the recipe grammar.
     * @param <E> type of the exception thrown by the {@link #visit(String, TokenGroup)} method
     */
    public interface Visitor<E extends Exception> {
        void visit(String command, TokenGroup tokenGroup) throws E;
    }

    public GrammarWalker(Compiler compiler, DirectiveContext context) {
        this.compiler = compiler;
        this.context = context;
    }

    /**
     * Walks the grammar tree generated by the recipe.
     *
     * @param recipe the recipe to parse
     * @param visitor the visitor for walking the grammar tree
     * @param <E> type of exception that can be thrown by the visitor
     * @throws CompileException if failed to compile the recipe
     * @throws DirectiveParseException if a directive in the recipe is invalid
     * @throws E if the visitor throws an exception
     */
    public <E extends Exception> void walk(String recipe,
                                           Visitor<E> visitor) throws CompileException, DirectiveParseException, E {
        CompileStatus status = compiler.compile(recipe);
        if (!status.isSuccess()) {
            Iterator<SyntaxError> errors = status.getErrors();
            String prefix = "Encountered syntax error, please ensure the directive is valid:\n";
            throw new DirectiveParseException(prefix + errors.next().getMessage(), errors);
        }

        Iterator<TokenGroup> tokenGroups = status.getSymbols().iterator();
        while (tokenGroups.hasNext()) {
            TokenGroup tokenGroup = tokenGroups.next();
            if (tokenGroup == null) {
                continue;
            }
            String command = ((DirectiveName) tokenGroup.get(0)).value();
            String root = command;
            if (context.hasAlias(root)) {
                root = context.getAlias(command);
            }

            // Checks if the directive has been excluded from being used.
            if (!root.equals(command) && context.isExcluded(command)) {
                throw new DirectiveParseException(
                    command, String.format("Aliased directive '%s' has been configured as restricted directive and "
                                           + "is hence unavailable. Please contact your administrator", command)
                );
            }

            if (context.isExcluded(root)) {
                throw new DirectiveParseException(
                    command, String.format("Directive '%s' has been configured as restricted directive and is hence "
                                           + "unavailable. Please contact your administrator", command));
            }

            visitor.visit(root, tokenGroup);
        }
    }
}